# Generated by Django 3.0.8 on 2020-10-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20201001_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_items',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
