# Generated by Django 3.1.2 on 2020-11-05 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cd_out_of_stock'),
        ('checkout', '0009_auto_20201105_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='cd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.cd'),
        ),
    ]
