# Generated by Django 3.1.2 on 2020-10-03 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Album',
            new_name='Photo',
        ),
    ]
