# Generated by Django 3.1.3 on 2020-11-10 09:26

import album.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_auto_20201007_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=album.models.random_filename),
        ),
    ]
